# å½“å‰ç‰ˆæœ¬ | Theme Version
Hexo: "2.1"

# ç½‘ç«™æ ‡é¢˜ | Title
logo_title: Kalvin's Blog

# åˆå§‹åŒ–é£æ ¼ | Default Style "black/light"
# style: black
style: light

#SEOä¼˜åŒ– | SEO settings

## ç½‘ç«™æè¿° | Description
description: Golang,PHP Developer

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰² | Keywords
keywords: Blog,Hexo,Theme,åˆ˜è®­ç¼,LiuXunzhuo

# é¦–é¡µURL | Your URL
link: https://simpleKalvin.github.io/blog

#æ ‡è¯­ | Your Slogan
words: Golang,PHP Developer

# ä½ çš„æ˜µç§° | Your Name
author: Kalvin

# ä¸­å¿ƒå›¾æ ‡é€‰æ‹©ç”·å¥³æˆ–è€…è‡ªå®šä¹‰ | Gender
gender: /img/me.jpg #/img/female.png

# ç«™ç‚¹å°å›¾æ ‡åœ°å€ | Small Icon of Your Site
# favicon: /img/favicon.ico
favicon: /img/site.png

# èœå•æ é…ç½® | Nav Bar Settings
menu:
  å…³äºæˆ‘ğŸ‘€: /about
  è®¿é—®ä¸»ç«™ğŸ‰: https://simpleKalvin.github.io/blog
  GitHubğŸ’: https://github.com/simpleKalvin

# ç«™å†…å…³é”®è¯æœç´¢ | Local Search
search:
  enable: true
  path: search.xml
  field: post
  # onload: true

# Valine è¯„è®ºç³»ç»Ÿ | Comments of Valine
## è¯·æ”¹æˆè‡ªå·±çš„ KEY ï½œ Replace Your Own Key
## è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalse
valine:
  enable: false
  appId: NOsswOncKgc8HOxqo9oxIWlX-gzGzoHsz
  appKey: z1FihjWEbS8uIfUQdmCtK7zz

# ä»£ç é«˜äº® ï½œ Code Highlight
highlight:
  enable: true
